name: train-my-model
on: [push]
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          TB_CREDENTIALS: ${{ secrets.TB_CRED }}
        run: |          
          pip install -r requirements.txt 
          cml tensorboard-dev \
            --logdir logs \
            --name "Go to tensorboard" \
            --md >> report.md
          cml send-comment report.md
 
          python train.py
